void setup() {
  Serial.begin(9600);
}

void loop() {
  // put your main code here, to run repeatedly:
    Serial.println("In periferia fa molto caldo \nMamma stai tranquilla sto arrivando \nTe la prenderai per un bugiardo \nTi sembrava amore ma era altro \nBeve champagne sotto Ramadan \nAlla TV danno Jackie Chan \nFuma narghilè mi chiede come va \nMi chiede come va, come va, come va \nSai già come va, come va, come va \nPenso più veloce per capire se domani tu mi fregherai \nNon ho tempo per chiarire perché solo ora so cosa sei \nÈ difficile stare al mondo quando perdi l'orgoglio \nLasci casa in un giorno \nTu dimmi se \nPensavi solo ai soldi, soldi \nCome se avessi avuto soldi, soldi \nDimmi se ti manco o te ne fotti, fotti \nMi chiedevi come va, come va, come va \nAdesso come va, come va, come va \nCiò che devi dire non l'hai detto \nTradire è una pallottola nel petto \nPrendi tutta la tua carità \nMenti a casa ma lo sai che lo sa \nSu una sedia lei mi chiederà \nMi chiede come va, come va, come va \nSai già come va, come va, come va \nPenso più veloce per capire se domani tu mi fregherai \nNon ho tempo per chiarire perché solo ora so cosa sei \nÈ difficile stare al mondo \nQuando perdi l'orgoglio \nHo capito in un secondo che tu da me \nVolevi solo soldi \nCome se avessi avuto soldi, soldi \nPrima mi parlavi fino a tardi, tardi \nMi chiedevi come va, come va, come va\nAdesso come va, come va, come va \nWaladi, waladi, habibi ta'aleena \nMi dicevi giocando giocando con aria fiera \nWaladi, waladi, habibi sembrava vera \nLa voglia, la voglia di tornare come prima \nIo da te non ho voluto soldi \nÈ difficile stare al mondo \nQuando perdi l'orgoglio \nLasci casa in un giorno \nTu dimmi se \nVolevi solo soldi, soldi \nCome se avessi avuto soldi, soldi \nLasci la città ma nessuno lo sa \nIeri eri qua ora dove sei, papà \nMi chiedi come va, come va, come va \nSai già come va, come va, come va");

}
